### ISSUE TITLE
RedirectSay effect is not interpreted

### ISSUE THREAD

**Issue by rexim** [tsoding/HyperNerd#224]
introduced in #222

**Comment by ear** [comment]
I wanted to see if it was possible to create something that would switch the interpreter dynamically.

I am using `GADTs` and `StandaloneDeriving` to have `Show a` instead of having to fix it as `String` in my constructors, otherwise it's just `EffectF = F` and `Effect = E`.

My [code in a gist](https://gist.github.com/ear/9b004fc7052947bff02f20cf724a0f32).

This has left me with some questions:

- is there a simpler way to write `runC (Free (Rand next)) = runIO rand >>= runC . next` ? Can't help but think there's a `fmap`/`lift?` version that's even simpler and might be more general, but I can't see it right now.
- the mutually recursive interpreters are very nice but I would like to see other approaches too

Thanks for the inspiration to delve into this!

**Comment by rexim** [comment]
> is there a simpler way to write `runL (Free (Rand next)) = runIO rand >>= runL . next` ?

I dunno. But this approach already looks simple enough to me.

> the mutually recursive interpreters are very nice but I would like to see other approaches too

I have a feeling that the other approaches simply utilize some kind of state and overall are not that interesting.

**P.S.** Interesting code, thanks! I think we may use a similar approach in the future.

**Comment by ear** [comment]
Update:

- remove stray `Show a` constraint in `Listen` (was wrongly `listen`ing to return values at the very beginning)
- handle return values of `E a` actions properly (they were ignored!)
- introduce the `listen_` action to ignore them explicitly

The tests are a bit random I wish I could come up with a more natural application of listening.
