### ISSUE TITLE
Piped commands print username multiple times

### ISSUE THREAD

**Issue by voldyman** [tsoding/HyperNerd#388]
In the example below, the username was printed multiple times
```shell
>voldyman: !quote 44 | !cycle
Moderator: @voldyman @VoLdYmAn tHiS SoUnDs gReAt: It's pRoBaBlY NoT GoNnA WoRk. 44
```

Adding another piped command adds the username again:

```
>voldyman: !quote 44 | !cycle | !russify
Moderator: @voldyman @vфldyмди @VфLdУмДи тHiS SфЦиDs gЯёДт: Iт's pЯфBдBlУ ИфT БфИиД ШфЯк. 44
```

**Comment by rexim** [comment]
Just for the record, the reason why this happens is because the commands that are used in this particular pipe respond with a `%sender` prefix. There is 3 commands in the pipe so the prefix was accumulated 3 times. This is needed to prevent Twitch command injection:

```
<mod> !addcmd foo %1 world
<mod> !foo hello
<bot> hello world
<mod> !foo /ban john
<bot> /ban john world
* bot banned john
```

But the problem is that sometimes this is exactly what we need (for example `!addcmd vanish /timeout %sender 1`)

We tried to address this in #390 by implementing a custom commands parameter which enables/disables Twitch command escaping. By default the output of custom commands is escaped unless we state otherwise.

After a second thought, I think this is not a good approach. A better approach would be:
- always escape everything the bot says (everything that comes through the `say` Effect),
- introduce a separate Effect for Twitch commands.

**Comment by rexim** [comment]
Or maybe we don't have to escape everything. Since the primary threat comes from the `%1` variable we can simply escape only that variable. :thinking:

**Comment by rexim** [comment]
@voldyman after #391 the particular pipe you provided in the description works as expected:

![2018-12-14-174703_333x219_scrot](https://user-images.githubusercontent.com/165283/50020780-9b329580-0009-11e9-80e8-264babe84cf4.png)

But some other commands may still have redundant `%sender` prefix responses. For those I created #392 and #393. So I suggested to close this issue.

**Comment by voldyman** [comment]
Awesome! I'll close this issue.

The change i was thinking of making would require a bigger refactor though.

```haskell
# pseduo haskell
request >>= parseCommand >>= (filterCommands . applyCommands) >>= buildResponse >>= sendResponse

# where 
data Request = Request sender message

parseCommand :: Request -> ParsedCommand
data ParsedCommand = ParsedCommand Request [Command]

filterCommands :: ParsedCommand -> Maybe ParsedCommand

data Response = Response to message
applyCommands :: ParsedCommand -> Response

sendResponse :: Response -> Effect ()
```
