### ISSUE TITLE
Alias should be able to use pipes to run two commands

### ISSUE THREAD

**Issue by rafaelffilho** [tsoding/HyperNerd#595]

**Comment by rexim** [comment]
Example: `!addalias supamarkov !markov | !russify`

**Comment by rexim** [comment]
@rafaelffilho I was thinking about implications this feature has. My conclusion is that we should not allow defining new commands in terms of existing commands, because that creates an opportunity for recursive commands handling of which is quite hard and way outside of the scope of this project at the moment. Most of the design inconsistency (that I mentioned on the stream) comes from that fact. We don't have any recursive commands handling -> it's hard to introduce a potentially recursive mechanism.

Existing aliases are not recursive:
https://github.com/tsoding/HyperNerd/tree/d55024546b9f860104af36c0bead4fbb4eec3354#command-aliases

Thank you for filing this issue though. It actually forced me to think about very important thing that I was unconsciously ignoring for some time. Let's close it for now and see how design evolves.
