### ISSUE TITLE
Bot replies with wrong username (the channel name) in twitch chat

### ISSUE THREAD

**Issue by zhiayang** [tsoding/HyperNerd#806]
So, I'm using the docker-compose setup. Couple of issues with this:

1. Bot produces no output on stdout or stderr, after the `Attaching to ...` line
2. Running via the `docker create ... && docker start` method, bot only prints to the console after Ctrl-C; while it's running nothing gets printed ):

Ok so the main issue here is that the bot uses my channel name to output (on chat), instead of the value of `nick`. This is the secret.ini:

```
[twitch]
nick = HyperNerd
channel = zhiayang
password = oauth:<lmao>
clientId = <kappa>
owner = zhiayang
```

Is this like wrong? When I mention the bot name (eg. via @HyperNerd), it does the mrbotka thing where it tries to respond with the markov chain (but there's nothing, because `markov.csv` is empty). so it knows to listen to the nick, but replies with the wrong user??

thanks

**Comment by rexim** [comment]
@zhiayang you have to own the account https://www.twitch.tv/hypernerd to be able to send messages from it (and it seems to be already taken). The problem is that Twitch doesn't have any special accounts for bots. They all are regular Twitch accounts that you have to create yourself, unfortunately. And you have to generate the oauth token from the bot account not yours.

**Comment by zhiayang** [comment]
AH OKAY

as expected i'm just a bit stupid. thanks!

**Comment by rexim** [comment]
@zhiayang No worries! Surprisingly enough, this is a pretty common mistake when it comes to Twitch bots. I guess platforms like Discord spoiled us a little bit.
